name: etl_assignment

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 3' # On wednesday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@main # checkout the repository content

      - name: setup python
        uses: actions/setup-python@main
        with:
          python-version: '3.9' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run ETL script
        id: etl_step
        run: |
          python YT_data_analysis_ETL.py
          ls -l

      - name: find the generated file
        id: file_name
        run: echo "FILE_NAME=$(ls extracted_data_*.csv)" >> $GITHUB_ENV

      - name: upload CSV file
        uses: actions/upload-artifact@v3
        with:
          name: extracted-data
          path: ${{ env.FILE_NAME }}
